version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: ./../docker/Dockerfile
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./composer.json:/app/composer.json
      - ./tests:/app/tests
    command: [ "composer", "run-script", "app" ]
